site_name: Softwrap Manual

nav:
    - Home: index.md
    - 'Getting started':
        - 'Instllation': 'installation.md'
        - 'Tutorials': 'tutorials.md'
        - 'Interface': 'interface.md'



theme: readthedocs


markdown_extensions:
    - admonition
    - attr_list
