
name: Deploy
on:
  push:
    branches: [ manual-mkdocs ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: manual-mkdocs
        
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: mkdocs install
        run: python -m pip install mkdocs

      - name: deploy
        run: |
          git config --global user.name Jeacom25b
          git config --global user.password ${{ secrets.GITHUB_TOKEN }}
          git config --global user.email 18407784+jeacom25b@users.noreply.github.com

          mkdocs gh-deploy
        shell: bash
